// haze-ui registry base — generated by scripts/generate-registry.mjs.
//
// Meta item: 'npx shadcn add wmzy/haze-ui/base' installs the entire
// design system — this theme-activation wrapper plus, through
// registryDependencies, a thin wrapper for every styled component under
// components/ui/haze/. The implementation keeps coming from the haze-ui
// npm package; edit the wrappers to customize.
//
// Theming (once per app): apply the token classes to a root element, e.g.
//   import { lightTheme, spacing, typography } from 'haze-ui';
//   <div className={`${lightTheme} ${spacing} ${typography}`}>…</div>
// (darkTheme is a drop-in swap).

import { compact, cyanTheme, darkTheme, lightTheme, motion, motionPresets, orangeTheme, roseTheme, spacing, tealTheme, typography, violetTheme } from 'haze-ui';

import 'haze-ui/css/tokens.css';

export { compact, cyanTheme, darkTheme, lightTheme, motion, motionPresets, orangeTheme, roseTheme, spacing, tealTheme, typography, violetTheme };
