// haze-ui registry wrapper — generated by scripts/generate-registry.mjs.
//
// This is a thin wrapper around the published haze-ui npm package, not
// vendored component source: it re-exports the component(s) from
// 'haze-ui' and imports their stylesheet, so the package keeps updating
// underneath. Edit this file to customize — wrap, restyle, compose; that
// is what it is for. (haze-ui is compiled CSS-in-JS (linaria) styled
// against --haze-* design tokens, so vendoring the source would neither
// build nor style — forking this wrapper is the intended customization
// path.)
//
// Theming (once per app): apply the token classes to a root element, e.g.
//   import { lightTheme, spacing, typography } from 'haze-ui';
//   <div className={`${lightTheme} ${spacing} ${typography}`}>…</div>
// (darkTheme is a drop-in swap). haze-ui dist modules ship their own
// 'use client' directive, so imports resolve cleanly from RSC; the
// wrapper inherits client semantics either way.

import { Kbd } from 'haze-ui';

import 'haze-ui/css/tokens.css';
import 'haze-ui/css/kbd.css';

export { Kbd };
export type { KbdProps } from 'haze-ui';
