allowBuilds:
  core-js: true
  esbuild: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - react-f0rm
  - '@native-router/*'
  - '@for-fun/event-emitter'
  - react-use-control@1.4.0 || 1.5.0
onlyBuiltDependencies:
  - core-js
  - unrs-resolver
