import type {TokenDef} from '@/lib';

import {TOKEN_REGISTRY} from '@/lib';

import {exportThemeCss} from './export-theme';

/** Small hand-written registry: deterministic fixture for exact-format work. */
const FIXTURE: TokenDef[] = [
  {name: '--haze-color-primary', category: 'color', label: 'Primary', type: 'color', light: 'oklch(0.5 0.2 264)', dark: 'oklch(0.7 0.15 264)'},
  {name: '--haze-radius-md', category: 'radius', label: 'Radius MD', type: 'size', light: '6px', dark: '8px'},
  {name: '--haze-text-sm', category: 'typography', label: 'Text SM', type: 'size', light: '14px', dark: '14px'},
];

/** Default (no edits) maps — empty records. */
const NO_EDITS = {light: {}, dark: {}};

describe('exportThemeCss', () => {
  it('exports only tokens that differ from the registry defaults', () => {
    const css = exportThemeCss(
      {light: {'--haze-color-primary': '#8b5cf6'}, dark: {'--haze-radius-md': '10px'}},
      {registry: FIXTURE},
    );

    expect(css).toContain('--haze-color-primary: #8b5cf6;');
    expect(css).toContain('--haze-radius-md: 10px;');
    expect(css).not.toContain('--haze-text-sm');
    // Default values never leak into a changed-only export.
    expect(css).not.toContain('oklch(0.5 0.2 264)');
    expect(css).not.toContain('8px');
  });

  it('treats edits equal to the default as unchanged', () => {
    const css = exportThemeCss(
      {
        light: {'--haze-color-primary': 'oklch(0.5 0.2 264)'},
        dark: {'--haze-text-sm': '14px'},
      },
      {registry: FIXTURE},
    );

    expect(css).toBe('');
  });

  it('emits independent light and dark blocks', () => {
    const lightOnly = exportThemeCss({light: {'--haze-text-sm': '13px'}, dark: {}}, {registry: FIXTURE});
    expect(lightOnly).toContain(':root {');
    expect(lightOnly).not.toContain('.dark {');

    const darkOnly = exportThemeCss({light: {}, dark: {'--haze-text-sm': '13px'}}, {registry: FIXTURE});
    expect(darkOnly).toContain('.dark {');
    expect(darkOnly).not.toContain(':root {');
  });

  it('exports every registry token with its per-mode default in all scope', () => {
    const css = exportThemeCss(NO_EDITS, {registry: FIXTURE, scope: 'all'});

    const rootBlock = css.slice(css.indexOf(':root {'), css.indexOf('.dark {'));
    const darkBlock = css.slice(css.indexOf('.dark {'));

    expect(rootBlock).toContain('--haze-color-primary: oklch(0.5 0.2 264);');
    expect(rootBlock).toContain('--haze-radius-md: 6px;');
    expect(rootBlock).toContain('--haze-text-sm: 14px;');
    expect(darkBlock).toContain('--haze-color-primary: oklch(0.7 0.15 264);');
    expect(darkBlock).toContain('--haze-radius-md: 8px;');
  });

  it('matches the exact expected format', () => {
    const css = exportThemeCss(
      {light: {'--haze-color-primary': '#8b5cf6'}, dark: {'--haze-radius-md': '10px'}},
      {registry: FIXTURE},
    );

    expect(css).toBe(`/* haze-ui theme overrides — generated by the Theme Editor.
   Light values target :root; dark values target \`.dark\` — swap in your
   own dark-mode selector (e.g. [data-theme='dark']) as needed. */

:root {
  --haze-color-primary: #8b5cf6;
}

.dark {
  --haze-radius-md: 10px;
}
`);
  });

  it('returns an empty string when nothing changed', () => {
    expect(exportThemeCss(NO_EDITS, {registry: FIXTURE})).toBe('');
  });

  it('uses TOKEN_REGISTRY defaults and registry order by default', () => {
    const primary = TOKEN_REGISTRY[0];
    if (!primary) throw new Error('TOKEN_REGISTRY is empty');
    const css = exportThemeCss({light: {[primary.name]: '#8b5cf6'}, dark: {}});

    const body = css.slice(css.indexOf('{'), css.indexOf('}'));
    expect(body).toBe(`{\n  ${primary.name}: #8b5cf6;\n`);

    // One block only, and the export declares tokens in registry order —
    // a real-registry smoke check on top of the fixture tests.
    expect(css).toContain(':root {');
    expect(css).not.toContain('.dark {');
  });
});
