import type {TokenDef} from '@/lib';

import {TOKEN_REGISTRY} from '@/lib';

/** Per-mode edit maps from the Theme Editor: token name → edited value. A
 * missing key (or an entry equal to the registry default) means "default". */
type ThemeEdits = {
  light: Record<string, string>;
  dark: Record<string, string>;
};

/** Which tokens land in the export: only real overrides, or the whole set. */
type ExportScope = 'changed' | 'all';

type ExportOptions = {
  /** Defaults to `'changed'`. */
  scope?: ExportScope;
  /** Defaults to `TOKEN_REGISTRY`; override for tests and subsets. */
  registry?: TokenDef[];
};

const HEADER_COMMENT = [
  '/* haze-ui theme overrides — generated by the Theme Editor.',
  '   Light values target :root; dark values target `.dark` — swap in your',
  "   own dark-mode selector (e.g. [data-theme='dark']) as needed. */",
].join('\n');

/** Render one CSS block from resolved name/value pairs. */
function formatBlock(selector: string, entries: [string, string][]): string {
  const body = entries.map(([name, value]) => `  ${name}: ${value};`).join('\n');
  return `${selector} {\n${body}\n}`;
}

/** Resolve the entries for one mode, in registry order. */
function modeEntries(
  mode: 'light' | 'dark',
  edits: ThemeEdits,
  registry: TokenDef[],
  scope: ExportScope,
): [string, string][] {
  const entries: [string, string][] = [];
  for (const token of registry) {
    const fallback = mode === 'light' ? token.light : token.dark;
    const effective = edits[mode][token.name] ?? fallback;
    // An edit equal to the default is not an override — mirrors the
    // editor's own diffing in buildChangedTokens (saved themes load full
    // maps, so equality must not count as a change).
    if (scope === 'changed' && effective === fallback) continue;
    entries.push([token.name, effective]);
  }
  return entries;
}

/**
 * Serialize the editor state to standalone CSS custom-property overrides.
 *
 * Light values are emitted on `:root`, dark values on `.dark`, in registry
 * order, with one `--haze-*: value;` declaration per line. Returns an empty
 * string when the chosen scope resolves to no tokens at all, so callers can
 * use the result directly as an "exportable yet?" signal. Pure: no DOM, no
 * timestamps — identical input always yields identical output.
 */
function exportThemeCss(edits: ThemeEdits, {scope = 'changed', registry = TOKEN_REGISTRY}: ExportOptions = {}): string {
  const blocks: string[] = [];

  const light = modeEntries('light', edits, registry, scope);
  if (light.length > 0) blocks.push(formatBlock(':root', light));

  const dark = modeEntries('dark', edits, registry, scope);
  if (dark.length > 0) blocks.push(formatBlock('.dark', dark));

  if (blocks.length === 0) return '';
  return `${HEADER_COMMENT}\n\n${blocks.join('\n\n')}\n`;
}

export {exportThemeCss};
export type {ThemeEdits, ExportScope, ExportOptions};
